### ISSUE TITLE
Not working with the latest version of form tools

### ISSUE THREAD

**Issue by madappally** [formtools/module-field_type_google_maps#1]
I've installed this module with Form Tools 2.2.6. But it's not working or not displaying in field type

**Comment by benkeen** [comment]
Hi @foranastes, are there any errors in your javascript console? I know this module worked fine so if there isn't a problem with your installation, possibly Google Maps has been updated and is no longer compatible. A javascript error might reveal something.

**Comment by benkeen** [comment]
This is now moot - FT3 is out and the module has been updated to support it.
