### ISSUE TITLE
Button Location - Future Request

### ISSUE THREAD

**Issue by nelsondcosta23** [formtools/module-field_type_google_maps#2]
Hello,

There is any way that a person by clicking on the location button will immediately appear in the field the location? This using a smartphone.

**Comment by benkeen** [comment]
Good call. There's actually a lot of stuff that needs to be done to make the app responsive. The plan is to cover that in FT 3.2.

**Comment by benkeen** [comment]
With 2.1.0 I've added a new button to the map that focuses the map on their location. Closing.
